# docker-compose up -d
version: '3.7'
services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: scoreit
    ports:
      - 5432:5432
    networks:
      - scoreit-network

  # service for local docker image
  scoreit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scoreit
    restart: always
    ports:
      - 8080:8080
      - 9090:9090
    networks:
      - scoreit-network
    depends_on:
      - postgres
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/scoreit?sslmode=disable
      - DB_DRIVER=postgres
      - MIGRATION_URL=file://db/migration
      - TOKEN_SYMMETRIC_KEY=12345678901234567890123456789012
      - ACCESS_TOKEN_DURATION=15m
      - REFRESH_TOKEN_DURATION=24h
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
networks:
  scoreit-network:
    driver: bridge