// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Team struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserTeam struct {
	ID              int32     `json:"id"`
	Number          int32     `json:"number"`
	PrimaryPosition string    `json:"primary_position"`
	UserID          uuid.UUID `json:"user_id"`
	TeamID          int32     `json:"team_id"`
	CreatedAt       time.Time `json:"created_at"`
}
