Project score_it {
  database_type: 'PostGreSQL'
  Note: '''
    # Scoreit Team Database
  '''
}

Table users as U {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    username varchar [not null]
    first_name varchar [not null]
    last_name varchar [not null]
    email varchar [unique, not null]
    is_email_verified boolean [not null, default: false]
    hashed_password varchar [not null]
    password_changed_at timestamptz [not null, default: '0001-01-01 00:00:00Z']
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz [not null, default: `now()`]
    Indexes {
        (username)[unique]
    }
}

Table verify_emails {
  id uuid [pk, default: `uuid_generate_v4()`, not null]
  user_id varchar [ref: > U.id, not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used boolean [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + interval '15 minutes'`]
  Indexes {
    (secret_code) [unique]
  }
}

Table teams as T {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    name varchar [not null]
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz [not null, default: `now()`]
    Indexes {
        (name)[unique]
    }
}

Table user_teams as UT {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    number int [not null]
    primary_position varchar [not null]
    user_id uuid [ref: > U.id, not null]
    team_id uuid [ref: > T.id, not null]
    created_at timestamptz [not null, default: `now()`]
}