Project score_it {
  database_type: 'PostGreSQL'
  Note: '''
    # Scoreit Team Database
  '''
}

Table users as U {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    username varchar [not null]
    first_name varchar [not null]
    last_name varchar [not null]
    created_at timestamptz [not null, default: `now()`]
    updated_at timestamptz [not null, default: `now()`]
    Indexes {
        (username)[unique]
    }
}

Table teams as T {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    name varchar [not null]
    created_at timestamptz [not null, default: `now()`]
}

Table user_teams as UT {
    id uuid [pk, default: `uuid_generate_v4()`, not null]
    number int [not null]
    primary_position varchar [not null]
    user_id uuid [ref: > U.id, not null]
    team_id uuid [ref: > T.id, not null]
    created_at timestamptz [not null, default: `now()`]
}