name: Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: scoreit
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.22

      - name: Install golang migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz  | tar xvz
          sudo mv migrate /usr/local/bin/
          which migrate

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest

      - name: Test Report
        run: make test_report

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Go Tests            # Name of the check run which will be created
          path: report.xml   # Path to test results
          reporter: java-junit

      - name: SonarCloud Scan
        # You may pin to the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@5875562561d22a34be0c657405578705a169af6c
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        if: always()
        with: { }
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

